version: '3.1'

services:
  app:
    image: 'app:<TAG>'
    restart: always
    container_name: app
    ports:
      - '13331:80'
    volumes:
      - '/home/bingo/runtime:/ai-bingo'
    environment:
      LEVEL: ${LEVEL}
      DB_USERNAME: ${DB_USERNAME}
      DB_SECRET: ${DB_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}